- hosts: webservers
  become: true
  become_user: root
  tasks:
   - name: install docker package
     yum: name=docker state=present
   - name: start docker service
     service: name=docker state=started
   - name: run the image devopsedu/webapp
     command: docker run -itd -P devopsedu/webapp
